POST http://localhost:8000/login/main-admin/
Content-Type: application/json

{
    "email":"admin1@anurag.edu.in",
    "password":"admin1"
}

###
POST http://localhost:8000/floor-data/add/floor/boys
Content-Type: application/json

{
    "floorNo":1
}

###
GET http://localhost:8000/floor-data/boys


###
DELETE  http://localhost:8000/floor-data/delete/boys/dd6d9a6e-bbc9-44e6-94dd-2d10d910abce

// Get the id from the "GET http://localhost:8000/boys/floor-data" request

###
POST http://localhost:8000/floor-data/add/floor/girls
Content-Type: application/json

{
    "floorNo":1,
    "numberOfRooms":50
}

###
GET http://localhost:8000/floor-data/girls


###
DELETE  http://localhost:8000/floor-data/delete/girls/9b45123f-4980-4d60-bba1-7bb3511a61c2

// Get the id from the "GET http://localhost:8000/girls/floor-data" request


###
Post http://localhost:8000/room-data/add/room/boys
Content-Type: application/json

{
    "roomNo":101,
    "floorNo":1,
    "totalStudents":4,
    "roomType":"non-ac",
    "washroomType":"attached"
}

###
GET http://localhost:8000/room-data/boys

###
DELETE http://localhost:8000/room-data/delete/boys/21f989d6-744f-476d-bae5-52ba3573c8d4

###
Post http://localhost:8000/room-data/add/room/girls
Content-Type: application/json

{
    "roomNo":101,
    "floorNo":1,
    "totalStudents":4,
    "roomType":"non-ac",
    "washroomType":"attached"
}

###
GET http://localhost:8000/room-data/girls

###
DELETE http://localhost:8000/room-data/delete/girls/80cdc8ed-6fa9-4831-87d4-95e21750bef7