POST http://localhost:8000/login/main-admin/
Content-Type: application/json

{
    "email":"admin1@anurag.edu.in",
    "password":"admin1"
}

###

POST http://localhost:8000/add/admin/data
Content-Type: application/json

{
    "email":"admin2@anurag.edu.in",
    "password":"admin2",
    "admin_type":"admin",
    "hostel_type":"both",
    "name":"admin2"
}

###
GET http://localhost:8000/admin-data

###
DELETE http://localhost:8000/delete/admin-data/d742f811-bc4a-4d50-a4a8-42104905b313


###
POST http://localhost:8000/floor-data/add/floor/boys
Content-Type: application/json

{
    "floorNo":1
}

###
GET http://localhost:8000/floor-data/boys


###
DELETE  http://localhost:8000/floor-data/delete/boys/c5750f3c-b43c-4ef7-9a09-804cec284f94

// Get the id from the "GET http://localhost:8000/boys/floor-data" request

###
POST http://localhost:8000/floor-data/add/floor/girls
Content-Type: application/json

{
    "floorNo":1,
    "numberOfRooms":50
}

###
GET http://localhost:8000/floor-data/girls


###
DELETE  http://localhost:8000/floor-data/delete/girls/9b45123f-4980-4d60-bba1-7bb3511a61c2

// Get the id from the "GET http://localhost:8000/girls/floor-data" request


###
Post http://localhost:8000/room-data/add/room/boys
Content-Type: application/json

{
    "roomNo":106,
    "floorNo":1,
    "total":4,
    "roomType":"non-ac",
    "washroomType":"attached"
}

###
GET http://localhost:8000/room-data/boys/?room_type=&washroom_type=

###
DELETE http://localhost:8000/room-data/delete/boys/21f989d6-744f-476d-bae5-52ba3573c8d4

###
GET http://localhost:8000/room-data/student/f64cf883-522f-4611-8b8c-d7f4dd785dc0

###
Post http://localhost:8000/room-data/add/room/girls
Content-Type: application/json

{
    "roomNo":103,
    "floorNo":1,
    "total":4,
    "roomType":"non-ac",
    "washroomType":"attached"
}

###
GET http://localhost:8000/room-data/girls

###
DELETE http://localhost:8000/room-data/delete/girls/80cdc8ed-6fa9-4831-87d4-95e21750bef7


###
POST http://localhost:8000/student-data/add/student/boys
Content-Type: application/json

{
    "name":"Sesh",
    "hallTicket_number":"21EG112B33",
    "branch":"IT",
    "current_year":3,
    "room_no": 101,
    "gender":"Male",
    "mobile_number":7013680808
}

###
GET http://localhost:8000/student-data/boys

###
DELETE http://localhost:8000/student-data/delete/student/81381593-cebd-4dcc-8877-000df72d00d2